version: '3.9'

volumes:
  postgres_data: {}

services:
  server:
    build:
      context: .
    restart: on-failure
    working_dir: "/app"
    ports:
      - "9000:9000"
    depends_on:
      - db
    volumes:
      - ".:/app"
      - "/app/node_modules"

  db:
    image: 'postgres'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: '123456'
      POSTGRES_USER: 'root'
    volumes:
      - postgres_data:/var/lib/postgresql/data
