version: '3.9'

volumes:
  postgres_data: {}

services:
  server:
    build:
      context: .
    restart: on-failure
    ports:
      - '4000:4000'
    depends_on:
      - db

  db:
    image: 'postgres'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: '123456'
      POSTGRES_USER: 'root'
    volumes:
      - postgres_data:/var/lib/postgresql/data
